name: Run Daily Pools Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm run pools:uniswap:all

      - name: Commit and push changes to new branch
        run: |
          BRANCH_NAME="tech/pools-update"
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin

          if git ls-remote --exit-code --heads origin "$BRANCH_NAME"; then
            echo "Branch '$BRANCH_NAME' exists. Checking it out."
            git checkout "$BRANCH_NAME"
            git pull origin "$BRANCH_NAME"
          else
            echo "Branch '$BRANCH_NAME' does not exist. Creating it."
            git checkout -b "$BRANCH_NAME"
          fi

          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git add .
            git commit -m "Update pools $TIMESTAMP"
            git push origin "$BRANCH_NAME"
          fi